### ISSUE TITLE
readOnly: false option (and inline: true option)

### ISSUE THREAD

**Issue by AndyObtiva** [dmuy/MDTimePicker#10]
I noticed this option in a sample on this site (https://www.jqueryscript.net/time-clock/Material-Time-Picker-Plugin-jQuery-MDTimePicker.html):

`readOnly: false`

It isn't listed in the options though and doesn't do anything when set.

Are there plans to support it?! I'd like to be able to enter time by typing on the keyboard in addition to the GUI.

p.s. also, any plans to support an `inline: true` option too to embed the MDTimePicker directly in a body div instead of an input field?

**Comment by dmuy** [comment]
Hi @AndyObtiva,

I believe that blog post is outdated, and I'm not the one who posted it there. I removed the option `readOnly` on [version 1.0.2](https://github.com/dmuy/MDTimePicker/releases/tag/v1.0.2).

Also, I won't implement manual entry of time as it defeats the purpose of this plugin. And I don't want to complicate things by including a time parsing algorithm just to facilitate manual entry of time on the input field.

For the `inline` option, I will implement it maybe on the future updates. Thanks for taking interest on this plugin.
