### ISSUE TITLE
Feature Request: Should the AMPM button on the top of the picker be clickable to change the period?

### ISSUE THREAD

**Issue by JoshuaPelealu** [dmuy/MDTimePicker#11]
Hey there 👋,

So I was trying out the time picker which was amazing btw. Anyway, I just had a little problem with it, the AMPM button cannot be clicked to toggle the period. I have solved this problem by changing the source code locally. It was a simple change, but I just wanted to maybe put this feature live so people do not have to implement it themselves.

Sincerely,

Catalactics (Joshua Pelealu)

**Comment by dmuy** [comment]
Implemented on https://github.com/dmuy/MDTimePicker/commit/b5f122ba3a9a86138ee1b0717bab5b5b7bdf1ad2
