### ISSUE TITLE
Uncaught TypeError: $(...).mdtimepicker is not a function

### ISSUE THREAD

**Issue by LeandroGames** [dmuy/MDTimePicker#12]
<link rel="stylesheet" type="text/css" href="assets/vendor/mdtimepicker/mdtimepicker.css">4
   <script src="assets/vendor/jquery3/jquery.min.js"></script>
    <script src="assets/vendor/bootstrap4/js/bootstrap.bundle.min.js"></script>
    <script src="assets/vendor/fontawesome5/js/solid.min.js"></script>
    <script src="assets/vendor/fontawesome5/js/fontawesome.min.js"></script>
    
    <script type="text/javascript" src="assets/vendor/mdtimepicker/mdtimepicker.js"></script>

    <script src="assets/js/script.js"></script>
    <script>
        $('.timepicker').mdtimepicker(); // Initialize time picker
    </script>
    
    "Uncaught TypeError: $(...).mdtimepicker is not a function"
    
    I'm trying to use it that way and get this error, how can I solve it?

**Comment by dmuy** [comment]
Hi @LeandroGames,

Are you using the jQuery version or the latest (v2)?

**Comment by LeandroGames** [comment]
Hi @dmuy!
I'm using jQuery 3.5.1

**Comment by dmuy** [comment]
Hi @LeandroGames,

I meant the version of MDTimePicker you are using.

**Comment by LeandroGames** [comment]
Hi @dmuy!
I'm using current version

**Comment by dmuy** [comment]
Hi @LeandroGames,

I see, then you're using it the wrong way (old version) - version 2 doesn't require jQuery anymore. Please take a look at the [wiki](https://github.com/dmuy/MDTimePicker/wiki/Usage).

**Comment by LeandroGames** [comment]
Thanks @dmuy
