### ISSUE TITLE
Set DEFAULTS

### ISSUE THREAD

**Issue by IZSkiSurfer** [dmuy/MDTimePicker#18]
In the older jQuery version was a way to set defaults like so:
`$.extend($.fn.mdtimepicker.defaults, {
	timeFormat: 'hh:mm:ss.000',
	format: 'hh:mm',
	theme: 'custom',
	readOnly: true,
	hourPadding: false,
	strCancel: 'stornieren',
	strOk: 'Ok',
	is12Hour: false
});`

This should be implemented again in a similar way..

**Comment by dmuy** [comment]
Implemented on https://github.com/dmuy/MDTimePicker/commit/ca9defa65958cb8e3758f5da5d8f40a87d62ae62.
Will be included on the next version release.

**Comment by IZSkiSurfer** [comment]
Thanks ;)

PS: have a look @ https://github.com/dmuy/MDTimePicker/commit/ca9defa65958cb8e3758f5da5d8f40a87d62ae62#diff-d404659e085c02bd4a95995119db33f0096d46b82c96f144b666fb14236a8bc3R904 - seems wrong to me
