### ISSUE TITLE
Code-Typo in Wiki

### ISSUE THREAD

**Issue by wug-ge** [dmuy/MDTimePicker#35]
Hey,

under the Nuxt 3 section there is following line as an example:
`  nextApp.vueApp.use(vueTimePicker, { theme: 'dark', is24hour: true })`

However, it just be "nuxtApp", not "nextApp", little annoying when copy pasting.

Thanks for this project BTW!

**Comment by dmuy** [comment]
Thank you for pointing it out @wug-ge, appreciate it. And I'm glad this project helped you in a way.
