### ISSUE TITLE
PM reverts back to AM on timepicker close

### ISSUE THREAD

**Issue by gjerdav** [dmuy/MDTimePicker#4]
I've run into an odd behavior with the AM/PM response from the timepicker.  Here's how to reproduce it:

- Set the input field to a PM time (I used 1:00PM)
- Open the timepicker by clicking on the field
- Change the hour to 12 specifically.
- Do not click the AM/PM indicators.  PM will still be highlighted.
- Click OK.
- Value placed back into input field will now say 12:00AM, not 12:00PM.

The issue seems to be specific to a time that starts as a PM time and is changed specifically to a "12" hour (changing from 2:00PM to 1:00PM returns 1:00PM like it should).

I have the timepicker configured with the following settings:
theme: 'blue',
format: 'h:mmtt',
hourPadding: false,
readOnly: true

I briefly tried using a format of 'hh:mmtt' to test 24-hour mode, and in those cases I got a 00:00 time back instead of a 12:00 time (consistent with the issue outlined above).

Any suggestions?  I took a look at the javascript file, but unfortunately my JavaScript skills aren't up to the task yet.

I'm testing with Firefox 60.0.1 64-bit on Linux (Ubuntu Studio).

Thanks!

**Comment by dmuy** [comment]
Hi @gjerdav,

Thank you for this, I didn't notice this one. I've fixed this bug on the latest [commit](https://github.com/dmuy/MDTimePicker/commit/eaa56da680515a6e8d6ebe5bc773672999ca7ae8)

**Comment by gjerdav** [comment]
Just downloaded the new version.  Looks great!  Thank you!!!
