### ISSUE TITLE
Suggenstion: add custom theme as option

### ISSUE THREAD

**Issue by NathalieSpierings** [dmuy/MDTimePicker#7]
Suggenstion:
It would be great if a custom theme could be passed as an option.
Now i overrule the default theme but if i can pass the theme name as an option i do not have to overrule the default theme.

**Comment by dmuy** [comment]
Implemented on [**c5082c6**](https://github.com/dmuy/MDTimePicker/commit/c5082c6679d225c2bee1ab14f8b00fa732a2c2de)
