### ISSUE TITLE
Can you tell how to preselected time in time pickers

### ISSUE THREAD

**Issue by naveedali8086** [dmuy/MDTimePicker#8]
Also when we edit the form, we have timepicker's value that we got while creating a form, how to show the preselected time in picker?

**Comment by dmuy** [comment]
Hi @naveedali8086,

There are two ways on how to set the time:

1. Setting the input's `value` before initializing the timepicker.
2. Using the `setValue` function of the timepicker instance.

To do number 2, you need to get the timepicker instance by calling the `.data('mdtimepicker')` after the initialization and assigning it to a variable:
```javascript
var picker = $('#picker').mdtimepicker({ readOnly: false, hourPadding: true, theme: 'dark' })
    .data('mdtimepicker');

// set the value by calling setValue
picker.setValue('03:00 PM');
```
_Note: If you changed the `format` configuration, you should use that format when setting the time_
